CREATE UNIQUE INDEX ux_bots_slug ON bots(slug);
CREATE UNIQUE INDEX ux_funnel_event_id ON funnel_events(event_id);
CREATE INDEX ix_funnel_created_at ON funnel_events(created_at);
CREATE INDEX ix_funnel_event ON funnel_events(event);
CREATE INDEX ix_funnel_bot_id ON funnel_events(bot_id);
CREATE INDEX ix_logs_created_at ON app_logs(created_at);
CREATE INDEX ix_logs_request_id ON app_logs(request_id);
CREATE INDEX ix_logs_event_id ON app_logs((meta->>'event_id'));
CREATE INDEX ix_media_bot_id ON media_assets(bot_id);
CREATE INDEX ix_users_bot_tg ON users(bot_id, tg_user_id);
